# Generated by Django 4.1.13 on 2026-04-18 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_conversation_student_is_mentor_student_mentor_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetakeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('retake', 'Retake Exam'), ('supplementary', 'Supplementary Exam')], default='retake', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retake_applications', to='api.enrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retake_applications', to='api.student')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('student', 'enrollment', 'exam_type')},
            },
        ),
    ]
